import { v4 as uuidv4 } from 'uuid';

export const data = {
    burgers: [
        {
            id: uuidv4(),
            price: '689',
            name: 'Мясная бомба',
            weight: '520',
            kkal: '430',
            description: 'Супер мясное наслаждение! Большая рубленая котлета из свежего говяжего мяса покорит вас своей сочностью, а хрустящие листья салата добавят свежести.',
            composition: 'Пшеничная булочка,Котлета из говядины,Красный лук,Листья салата,Соус горчичный',
            img: require('./resources/menu/meatbomb.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '550',
            name: 'Супер сырный',
            weight: '512',
            kkal: '430',
            description: 'Супер сырное наслаждение! Две большие рубленые котлеты из свежего говяжьего мяса заставят вас получить оргазм, а хрустящие маринованные огурцы добавят свежести.',
            composition: 'Пшеничная булочка,Две котлеты из говядины,Маринованные огурцы,Соус горчичный',
            img: require('./resources/menu/supercheese.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '580',
            name: 'Супер сытный',
            weight: '580',
            kkal: '550',
            description: 'Сытный бургер, наполненный лучшими ингредиентами, создающий гармонию вкусов.',
            composition: 'Пшеничная булочка,Котлета из говядины,Сыр,Листья салата,Помидоры,Соус BBQ',
            img: require('./resources/menu/satisfying.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '480',
            name: 'Тяжелый удар',
            weight: '470',
            kkal: '500',
            description: 'Бургер с мощной котлетой и насыщенным вкусом для истинных гурманов.',
            composition: 'Пшеничная булочка,Толстая котлета,Копченый бекон,Лук,Соус чили',
            img: require('./resources/menu/heavyblow.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '450',
            name: 'Вечная классика',
            weight: '450',
            kkal: '400',
            description: 'Классический бургер, который никогда не выйдет из моды. Простой, но всегда вкусный!',
            composition: 'Пшеничная булочка,Котлета из говядины,Листья салата,Помидоры,Соус кетчуп',
            img: require('./resources/menu/timelessclassic.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '560',
            name: 'Итальянский',
            weight: '510',
            kkal: '450',
            description: 'Итальянские специи и свежие ингредиенты в каждой порции! Бургер, который перенесет вас в Италию.',
            composition: 'Пшеничная булочка,Котлета из говядины,Моцарелла,Базилик,Томатный соус',
            img: require('./resources/menu/italian.png'),
            count: 1,
        },
    ],
    snacks: [
        {
            id: uuidv4(),
            price: '250',
            name: 'Начос',
            weight: '220',
            kkal: '300',
            description: 'Хрустящие начос, подаваемые с насыщенным сырным соусом.',
            composition: 'Кукурузные чипсы,Сырный соус,Перец,Огурцы',
            img: require('./resources/menu/nachos.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '245',
            name: 'Картошка фри',
            weight: '180',
            kkal: '350',
            description: 'Золотистая и хрустящая картошка фри, идеально подходит к любому блюду.',
            composition: 'Картофель,Соль,Масло растительное',
            img: require('./resources/menu/frenchfries.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '230',
            name: 'Луковые кольца',
            weight: '160',
            kkal: '320',
            description: 'Хрустящие луковые кольца, обжаренные до золотистой корочки.',
            composition: 'Лук,Тесто,Масло растительное',
            img: require('./resources/menu/onionrings.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '230',
            name: 'Кольца кальмара',
            weight: '130',
            kkal: '270',
            description: 'Хрустящие кольца кальмара, обжаренные до золотистой корочки.',
            composition: 'Кальмар,Тесто,Масло растительное',
            img: require('./resources/menu/calmarrings.jpg'),
            count: 1,
        },
    ],
    hotdogs: [
        {
            id: uuidv4(),
            price: '290',
            name: 'Домашний хот-дог',
            weight: '250',
            kkal: '400',
            description: 'Вкусный домашний хот-дог с сочной сосиской и свежими овощами.',
            composition: 'Булочка,Сосиска,Кетчуп,Горчица,Листья салата',
            img: require('./resources/menu/homehotdog.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '239',
            name: 'Жгучий хот-дог',
            weight: '245',
            kkal: '450',
            description: 'Острый хот-дог для любителей остренького! С перцем и острыми соусами.',
            composition: 'Булочка,Сосиска,Острый соус,Перец,Лук',
            img: require('./resources/menu/spicehotdog.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '220',
            name: 'Классический хот-дог',
            weight: '215',
            kkal: '350',
            description: 'Классика жанра — любимый многими хот-дог с минималистичным вкусом.',
            composition: 'Булочка,Сосиска,Кетчуп,Горчица',
            img: require('./resources/menu/classichotdog.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '300',
            name: 'Сытный хот-дог',
            weight: '300',
            kkal: '500',
            description: 'Классика жанра — любимый многими хот-дог с минималистичным вкусом.',
            composition: 'Булочка,Сосиска,Кетчуп,Горчица,бекон',
            img: require('./resources/menu/baconhotdog.jpg'),
            count: 1,
        },

    ],
    combo: [
        {
            id: uuidv4(),
            price: '540',
            name: 'Комбо 1',
            weight: '450',
            kkal: '700',
            description: 'Сытное комбо с бургером и картошкой фри, отличное решение для обеда.',
            composition: 'Бургер,Картошка фри,Напиток',
            img: require('./resources/menu/combo2.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '665',
            name: 'Комбо 2',
            weight: '650',
            kkal: '900',
            description: 'Большое комбо для настоящих голодных! Бургер, картошка и десерт.',
            composition: 'Бургер,Картошка фри,Десерт,Напиток',
            img: require('./resources/menu/combo1.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '800',
            name: 'Комбо 3',
            weight: '800',
            kkal: '1100',
            description: 'Максимальное наслаждение с большим бургером и разными закусками!',
            composition: 'Бургер,Супер картошка,Десерт,Напиток',
            img: require('./resources/menu/combo3.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '800',
            name: 'Комбо 4',
            weight: '1600',
            kkal: '2300',
            description: 'Три огромные пицца для компании!',
            composition: 'Пицца Мириталь,Пицца Помодоро,Пицца Веган',
            img: require('./resources/menu/combo4.png'),
            count: 1,
        },
    ],
    burrito: [
        {
            id: uuidv4(),
            price: '450',
            name: 'Шаурма "Иерусалим"',
            weight: '300',
            kkal: '500',
            description: 'Вкусная шаурма с мясом и свежими овощами, идеальная для перекуса.',
            composition: 'Тесто,Мясо,Огурцы,Помидоры,Соусы',
            img: require('./resources/menu/ierusalimburrito.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '490',
            name: 'Шаурма "Бахрома"',
            weight: '365',
            kkal: '550',
            description: 'Насыщенная шаурма с мясом и ароматными специями.',
            composition: 'Тесто,Мясо,Специи,Огурцы,Соус',
            img: require('./resources/menu/bahromaburrito.png'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '550',
            name: 'Шаурма "Петербург"',
            weight: '425',
            kkal: '600',
            description: 'Сытная шаурма с мясом и специальным соусом, которая оставит вас довольным.',
            composition: 'Тесто,Мясо,Соус,Лук,Помидоры',
            img: require('./resources/menu/peterburgburrito.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '490',
            name: 'Шаурма "Деревенская"',
            weight: '440',
            kkal: '500',
            description: 'Вкусная шаурма с брынзой и специальным соусом, которая оставит вас довольным.',
            composition: 'Тесто,Брынза,Соус,Лук,Помидоры',
            img: require('./resources/menu/brinzaburrito.jpg'),
            count: 1,
        },
    ],
    pizza: [
        {
            id: uuidv4(),
            price: '600',
            name: 'Пицца "Мириталь"',
            weight: '400',
            kkal: '800',
            description: 'Ароматная пицца с свежими ингредиентами и тонким тестом.',
            composition: 'Тесто,Сыр,Помидоры,Орегано,Мясо',
            img: require('./resources/menu/pizzamirital.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '650',
            name: 'Пицца "Помодоро"',
            weight: '450',
            kkal: '750',
            description: 'Пицца с помидорами и остренькой колбаской для настоящих любителей!',
            composition: 'Тесто,Сыр,Помидоры,Колбаса,Специи',
            img: require('./resources/menu/pizzapomodoro.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '700',
            name: 'Пицца "Веган"',
            weight: '390',
            kkal: '600',
            description: 'Веганская пицца с разнообразием свежих овощей и ароматным соусом.',
            composition: 'Тесто,Сыр растительный,Овощи,Соус',
            img: require('./resources/menu/pizzavegan.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '750',
            name: 'Пицца "Пеперони"',
            weight: '450',
            kkal: '800',
            description: 'Пицца Пеперони с насыщенным и слегка пикантным салями',
            composition: 'Тесто,Сыр растительный,Овощи,Салями,Соус',
            img: require('./resources/menu/pizzapeperoni.png'),
            count: 1,
        },
    ],
    wok: [
        {
            id: uuidv4(),
            price: '450',
            name: 'Вок "Спайси чесночный"',
            weight: '550',
            kkal: '700',
            description: 'Острый вок с чесноком и свежими овощами, идеален для любителей остроты.',
            composition: 'Лапша,Овощи,Соус,Чеснок',
            img: require('./resources/menu/wokspicygarlic.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '600',
            name: 'Вок "С креветками"',
            weight: '525',
            kkal: '800',
            description: 'Сытный вок с нежными креветками и овощами.',
            composition: 'Лапша,Креветки,Овощи,Соус',
            img: require('./resources/menu/wokshrimp.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '400',
            name: 'Вок "Веган"',
            weight: '400',
            kkal: '600',
            description: 'Веганский вок с набором свежих овощей и специями.',
            composition: 'Лапша,Овощи,Соус,Специи',
            img: require('./resources/menu/wokvegan.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '600',
            name: 'Вок "Миска"',
            weight: '550',
            kkal: '900',
            description: 'Миска вока которая не оставит вас голодного',
            composition: 'Лапша,Овощи,Соус,Специи,Креветки,Курица',
            img: require('./resources/menu/wokmiska.jpg'),
            count: 1,
        },
    ],
    deserts: [
        {
            id: uuidv4(),
            price: '250',
            name: 'Черный Принц',
            weight: '125',
            kkal: '350',
            description: 'Нежный десерт с шоколадом, который придется по вкусу всем сладкоежкам.',
            composition: 'Шоколад,Крем,Фрукты',
            img: require('./resources/menu/desertblackprince.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '200',
            name: 'Панакота ягодная',
            weight: '100',
            kkal: '250',
            description: 'Легкий и освежающий десерт на основе сливок и ягод.',
            composition: 'Сливки,Ягоды,Сахар',
            img: require('./resources/menu/desertpanacote.jfif'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '300',
            name: 'Тирамису',
            weight: '175',
            kkal: '400',
            description: 'Итальянский десерт с кофе и кремом, который нельзя пропустить.',
            composition: 'Кофе,Маскарпоне,Песочное печенье',
            img: require('./resources/menu/deserttiramisu.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '150',
            name: 'Эклер',
            weight: '85',
            kkal: '250',
            description: 'Знаменитый франццузский эклер.',
            composition: 'Заварное тесто,крем',
            img: require('./resources/menu/desertekler.jpg'),
            count: 1,
        },
    ],
    souces: [
        {
            id: uuidv4(),
            price: '50',
            name: 'Соус "Аджика"',
            weight: '25',
            kkal: '40',
            description: 'Острый соус на основе перца с ароматом специй.',
            composition: 'Перец,Специи,Соль',
            img: require('./resources/menu/souceadjika.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '50',
            name: 'Соус "Чесночный"',
            weight: '25',
            kkal: '30',
            description: 'Ароматный чесночный соус, идеально дополняет ваши блюда.',
            composition: 'Чеснок,Майонез,Специи',
            img: require('./resources/menu/soucegarlik.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '50',
            name: 'Соус "Острый"',
            weight: '25',
            kkal: '35',
            description: 'Острый соус для настоящих любителей остроты.',
            composition: 'Перец,Специи,Уксус',
            img: require('./resources/menu/soucehot.jpg'),
            count: 1,
        },
        {
            id: uuidv4(),
            price: '50',
            name: 'Соус "Сметанный"',
            weight: '25',
            kkal: '35',
            description: 'Соус на основе сметаны и зелени.',
            composition: 'Перец,Специи,Уксус',
            img: require('./resources/menu/creamsouce.jpg'),
            count: 1,
        },
    ],

    tabData: [
        { icon: require('../src/resources/icons/burger-icon.png'), label: 'Бургеры', key: 'burgers' },
        { icon: require('../src/resources/icons/onion-icon.png'), label: 'Закуски', key: 'snacks' },
        { icon: require('../src/resources/icons/hotdog-icon.png'), label: 'Хот-доги', key: 'hotdogs' },
        { icon: require('../src/resources/icons/combo-icon.png'), label: 'Комбо', key: 'combo' },
        { icon: require('../src/resources/icons/burrito-icon.png'), label: 'Шаурма', key: 'burrito' },
        { icon: require('../src/resources/icons/pizza-icon.png'), label: 'Пицца', key: 'pizza' },
        { icon: require('../src/resources/icons/wok-icon.png'), label: 'Вок', key: 'wok' },
        { icon: require('../src/resources/icons/deserts-icon.png'), label: 'Десерты', key: 'deserts' },
        { icon: require('../src/resources/icons/souce-icon.png'), label: 'Соуса', key: 'souces' },

    ],
};
